# SQL4A Configuration
# Конфигурация для SQL ассистента PostgreSQL

# Database settings
database:
  host: localhost
  port: 5432
  name: sql4a_db
  user: postgres
  password: postgres
  pool_size: 10
  max_overflow: 20

# AI/LLM settings
ai:
  # Ollama settings (local)
  ollama:
    base_url: "http://localhost:11434/v1"
    api_key: "ollama"
    model: "qwen2.5:7b"
    temperature: 0.1
    max_tokens: 2000
  
  # OpenAI settings (cloud)
  openai:
    api_key: ""  # Set your OpenAI API key here
    model: "gpt-4"
    temperature: 0.1
    max_tokens: 2000
  
  # Default provider (ollama or openai)
  provider: "ollama"

# RAG settings
rag:
  chunk_size: 1000
  chunk_overlap: 200
  max_context_docs: 5
  embedding_model: "all-MiniLM-L6-v2"
  vector_store: "chroma"  # chroma or faiss

# Application settings
app:
  title: "SQL4A - PostgreSQL SQL Assistant"
  description: "Интеллектуальный ассистент для работы с PostgreSQL"
  version: "1.0.0"
  debug: true
  log_level: "INFO"

# API settings
api:
  host: "0.0.0.0"
  port: 8000
  reload: true
  cors_origins: ["*"]

# Streamlit settings
streamlit:
  port: 8501
  theme:
    primary_color: "#1f77b4"
    background_color: "#ffffff"
    secondary_background_color: "#f0f2f6"

# Security
security:
  enable_auth: false
  secret_key: "your-secret-key-here"
  session_timeout: 3600  # seconds

# File upload settings
upload:
  max_file_size: 50MB
  allowed_extensions: [".pdf", ".txt", ".docx", ".sql"]
  upload_dir: "data/uploads"

# Knowledge base settings
knowledge_base:
  categories:
    - "Database Schema"
    - "SQL Examples"
    - "Best Practices"
    - "Troubleshooting"
    - "Performance Tips"
    - "Documentation"
  
  auto_schema_analysis: true
  schema_cache_ttl: 3600  # seconds

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/sql4a.log"
  max_size: 10MB
  backup_count: 5

